name: Build Proxy Container
on: 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/AzureAI.Proxy
  working-directory: ./src
  main-project-directory: "AzureAI.Proxy"
 
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
     
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 

    - name: Create a Lowercase Image Tag
      id: lowercase
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: ${{ env.working-directory }}
        file: ${{ env.working-directory }}/${{ env.main-project-directory}}/Dockerfile
        push: true
        tags: ${{ steps.lowercase.outputs.lowercase }}
        labels: ${{ steps.meta.outputs.labels }}
      

  